name: Landing.Page.as
tagline: Instant Landing Pages hosted on GitHub Pages
thumbnailUuid:
logoUuid:
whoText: "<p>Hi, I&#x27;m Nathan Clevenger</p>"
whatText: "<p>We are working on a new exciting product...</p>"
media:
whyText: "<p>Get early access before we launch on Product Hunt...</p>"
successText: "<p>Thank you for supporting our project!</p><p></p>"
templateName: default
brandColor: "#f64900"
backgroundColor: "#000"
backgroundImageUuid:
websiteUrl: https://landing.pages.as
appStoreUrl:
playStoreUrl:
facebookUrl:
twitterUrl:
angellistUrl:
privacyPolicyUrl:
hiring: false
status: unlisted
